databases:
  - name: postgres
    databaseName: task_manager
    user: task_manager
    region: frankfurt
    plan: free
    postgresMajorVersion: 13
    ipAllowList: []

services:
  - type: redis
    name: sidekiq-redis
    region: frankfurt
    maxmemoryPolicy: noeviction
    ipAllowList: []

  - type: worker
    name: sidekiq-worker
    runtime: ruby
    region: frankfurt
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: web
    name: task_manager
    runtime: ruby
    region: frankfurt
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec puma -C config/puma.rb
    envVars:
      - key: REDIS_HOST
        fromService:
          type: pserv
          name: task_manager-redis
          property: hostport
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: ROLLBAR_ACCESS_TOKEN
        sync: false
      - key: NEWRELIC_LICENSE_KEY
        sync: false

  - type: worker
    name: task_manager-sidekiq
    runtime: ruby
    region: frankfurt
    buildCommand: bundle install && bundle exec rake assets:precompile
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec sidekiq -e production
    envVars:
      - key: REDIS_HOST
        fromService:
          type: pserv
          name: task_manager-redis
          property: hostport
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: ROLLBAR_ACCESS_TOKEN
        sync: false
      - key: NEWRELIC_LICENSE_KEY
        sync: false

  - type: pserv
    name: task_manager-redis
    env: docker
    region: frankfurt
    repo: https://github.com/render-examples/redis.git
    numInstances: 1
    disk:
      name: task_manager-redis-data
      mountPath: /var/lib/redis
      sizeGB: 1
