name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: COVERALLS
    steps:
      - uses: actions/checkout@v2
      - name: Build and run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: docker-compose --file docker-compose.ci.yml run ci
      - name: Coveralls Report
        run: |
          docker cp ci:/task_manager/coverage .
          coveralls-lcov --repo-token ${{ secrets.COVERALLS_REPO_TOKEN }} coverage/lcov.info
